CREATE DATABASE IF NOT EXISTS Monitor;
USE Monitor;

CREATE TABLE IF NOT EXISTS Rooms(
    id SERIAL PRIMARY KEY,
    name VARCHAR (10) NOT NULL
);

CREATE TABLE IF NOT EXISTS Motes(
    id SERIAL PRIMARY KEY,
    roomId SERIAL FOREIGN KEY REFERENCES(Rooms.id)
    x SMALLINT UNSIGNED,
    y SMALLINT UNSIGNED
);

CREATE TABLE IF NOT EXISTS Measurements(
    id SERIAL PRIMARY KEY,
    moteId SERIAL,
    'timestamp' DATETIME NOT NULL,
    temperature DECIMAL (5,2) NOT NULL,
    humidity DECIMAL (5,2) NOT NULL,

    FOREIGN KEY moteId REFERENCES Motes.id
);
