CREATE DATABASE IF NOT EXISTS monitor;
USE monitor;

CREATE TABLE IF NOT EXISTS room(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    name VARCHAR (255) NOT NULL,
    floor SMALLINT UNSIGNED NOT NULL
);

CREATE TABLE IF NOT EXISTS mote(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    room_id INT NOT NULL,
    mote_id VARCHAR(255) NOT NULL,
    x SMALLINT UNSIGNED,
    y SMALLINT UNSIGNED,
    
    CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES room(id)
);

CREATE TABLE IF NOT EXISTS measurement(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT UNIQUE,
    mote_id INT NOT NULL,
    time_stamp DATETIME NOT NULL,
    temperature DECIMAL (5,2) NOT NULL,
    humidity DECIMAL (5,2) NOT NULL,

    CONSTRAINT fk_mote_id FOREIGN KEY (mote_id) REFERENCES mote(id)
);
