CREATE DATABASE IF NOT EXISTS monitor;
USE monitor;

CREATE TABLE IF NOT EXISTS floor(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    floor_no SMALLINT NOT NULL,
	floor_geojson VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS room(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    floor_id INT NOT NULL,
    name VARCHAR (255) NOT NULL,

	CONSTRAINT fk_floor_id FOREIGN KEY (floor_id) REFERENCES floor(id)
);

CREATE TABLE IF NOT EXISTS mote(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    room_id INT NOT NULL,
    node_id INT NOT NULL,
    mote_id VARCHAR(255) NOT NULL,
    x SMALLINT UNSIGNED,
    y SMALLINT UNSIGNED,
    
    CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES room(id)
);

CREATE TABLE IF NOT EXISTS measurement(
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    mote_id INT NOT NULL,
    time_stamp DATETIME NOT NULL,
    temperature DECIMAL (5,2) NOT NULL,
    humidity DECIMAL (5,2) NOT NULL,

    CONSTRAINT fk_mote_id FOREIGN KEY (mote_id) REFERENCES mote(id)
);
