INSERT INTO room(name, floor) VALUES("S101 Auditorium/Seminar Room", 1);
INSERT INTO room(name, floor) VALUES("S102 CiTech - Industry Transfer", 1);
INSERT INTO room(name, floor) VALUES("S103 CiTech - Project Engineers", 1);
INSERT INTO room(name, floor) VALUES("S120 Project Lab", 1);
INSERT INTO room(name, floor) VALUES("S120A Technical Support", 1);
INSERT INTO room(name, floor) VALUES("S121 The Couch", 1);
INSERT INTO room(name, floor) VALUES("S122A Project Lab", 1);
INSERT INTO room(name, floor) VALUES("S122B Undergrad Project Lab", 1);
INSERT INTO room(name, floor) VALUES("S122C Undergrad Project Lab", 1);
INSERT INTO room(name, floor) VALUES("S122D MSc Students Lab", 1);
INSERT INTO room(name, floor) VALUES("S122E Coffee Corner", 1);
INSERT INTO room(name, floor) VALUES("S201 Secretariat & IT Management", 2);
INSERT INTO room(name, floor) VALUES("S202", 2);
INSERT INTO room(name, floor) VALUES("S203 Kitchen", 2);
INSERT INTO room(name, floor) VALUES("S204", 2);
INSERT INTO room(name, floor) VALUES("S205 Cafeteria", 2);
INSERT INTO room(name, floor) VALUES("S206 Visitor Researchers", 2);
INSERT INTO room(name, floor) VALUES("S207 PhD Students Lab", 2);
INSERT INTO room(name, floor) VALUES("S207A", 2);
INSERT INTO room(name, floor) VALUES("S208", 2);
INSERT INTO room(name, floor) VALUES("S209 PhD Students Lab", 2);
INSERT INTO room(name, floor) VALUES("S210 PhD Students Lab", 2);
INSERT INTO room(name, floor) VALUES("S210A", 2);
INSERT INTO room(name, floor) VALUES("S211 Meeting Room", 2);
INSERT INTO room(name, floor) VALUES("S212 PhD Students Lab", 2);
INSERT INTO room(name, floor) VALUES("S212A", 2);
INSERT INTO room(name, floor) VALUES("S213", 2);
INSERT INTO room(name, floor) VALUES("S213A Prayer Room", 2);
INSERT INTO room(name, floor) VALUES("S213B Meeting Room", 2);
INSERT INTO room(name, floor) VALUES("S301 Library/PhD Student Classroom", 3);
INSERT INTO room(name, floor) VALUES("S302 BoD Meeting Room", 3);
INSERT INTO room(name, floor) VALUES("S303", 3);
INSERT INTO room(name, floor) VALUES("S304", 3);
INSERT INTO room(name, floor) VALUES("S306", 3);
INSERT INTO room(name, floor) VALUES("S307", 3);
INSERT INTO room(name, floor) VALUES("S308 Meeting Room", 3);
INSERT INTO room(name, floor) VALUES("S310", 3);
INSERT INTO room(name, floor) VALUES("S311", 3);
INSERT INTO room(name, floor) VALUES("S312", 3);
INSERT INTO room(name, floor) VALUES("S314", 3);
INSERT INTO room(name, floor) VALUES("S315", 3);
INSERT INTO room(name, floor) VALUES("S316", 3);
INSERT INTO room(name, floor) VALUES("S321 Data Centre", 3);

INSERT INTO mote(mote_id, room_id) VALUES("IE0032G", 1);
INSERT INTO mote(mote_id, room_id) VALUES("IE0033G", 1);